#!/usr/bin/env python3
"""
Visualizer for the MovieLens recommender-system experiment.

The input is the nested results.json generated by algorithms.py:

    {
        "Algorithm name": {
            "rating": {...},
            "ranking": {...},
            "timing": {...},
            "selected_choices": {...}
        }
    }

Charts
------
1. Raw and bounded rating errors.
2. Hit Rate, NDCG, and truncated MRR at K.
3. Raw RMSE versus NDCG at K.
4. Test-set rating prediction time.
5. Percentage of raw rating predictions outside the valid rating range.
6. Training and model-selection time.

Usage
-----
    python visualizer.py
    python visualizer.py Predictions
    python visualizer.py Predictions svg
    python visualizer.py Predictions pdf
    python visualizer.py Predictions png

The visualizer only reads results; it never runs the experiment. It loads the
supplied path (a results.json file, or a directory containing one — the
default directory is Predictions/). If no current-format algorithm results
are found, it terminates and names the required file. Run algorithms.py first
to produce Predictions/results.json.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Callable

import matplotlib

matplotlib.use("Agg")

import matplotlib.figure
import matplotlib.pyplot as plt
import numpy as np


BASE_DIR = Path(__file__).resolve().parent
DEFAULT_RESULTS_DIR = BASE_DIR / "Predictions"
OUTPUT_DIR = BASE_DIR / "charts"
# The essay (ib_cs_ee/essay.qmd) references figures/*.pdf directly. When the
# visualizer renders PDFs it also mirrors them here so the essay figures stay
# in sync with a single `python visualizer.py Predictions pdf`.
ESSAY_FIGURES_DIR = BASE_DIR / "ib_cs_ee" / "figures"
SUPPORTED_FORMATS = {"svg", "pdf", "png"}

ALGORITHM_DISPLAY = {
    "Global mean": ("Global mean", "#969696"),
    "Genre content profile": ("Genre", "#E69F00"),
    "Tag Genome content profile": ("Tag Genome", "#56B4E9"),
    "Tag Genome weighted hybrid": ("Genome hybrid", "#009E73"),
    "User-based k-NN": ("User k-NN", "#CC79A7"),
    "Movie-based k-NN": ("Movie k-NN", "#D55E00"),
    "Biased MF": ("Biased MF", "#0072B2"),
    "BPR-MF thresholded positives": ("BPR-MF", "#984EA3"),
    "MF+BPR hybrid": ("MF+BPR", "#E41A1C"),
}

ALGORITHM_FAMILIES = {
    "Global mean": "Baseline",
    "Genre content profile": "Content",
    "Tag Genome content profile": "Content",
    "Tag Genome weighted hybrid": "Hybrid",
    "User-based k-NN": "Neighborhood CF",
    "Movie-based k-NN": "Neighborhood CF",
    "Biased MF": "Latent factor",
    "BPR-MF thresholded positives": "Latent factor",
    "MF+BPR hybrid": "Hybrid",
}

ALGORITHM_ORDER = [
    "Global mean",
    "Genre content profile",
    "Tag Genome content profile",
    "Tag Genome weighted hybrid",
    "User-based k-NN",
    "Movie-based k-NN",
    "Biased MF",
    "BPR-MF thresholded positives",
    "MF+BPR hybrid",
]

plt.rcParams.update(
    {
        "font.size": 11,
        "font.weight": "normal",
        "axes.titlesize": 14,
        "axes.titleweight": "bold",
        "axes.labelsize": 12,
        "xtick.labelsize": 10,
        "ytick.labelsize": 10,
        "figure.dpi": 100,
        "savefig.facecolor": "white",
        "savefig.bbox": "tight",
        "savefig.pad_inches": 0.15,
        "axes.grid": True,
        "axes.axisbelow": True,
        "grid.alpha": 0.2,
        "grid.linestyle": "-",
        "axes.spines.top": False,
        "axes.spines.right": False,
    }
)


def is_algorithm_result(value: object) -> bool:
    """Return whether a value resembles the current result schema."""
    return (
        isinstance(value, dict)
        and isinstance(value.get("rating"), dict)
        and isinstance(value.get("ranking"), dict)
        and isinstance(value.get("timing"), dict)
    )


def load_results(path: str | Path) -> dict[str, dict[str, object]]:
    """Load current-format algorithm results from a file or directory."""
    source = Path(path)

    if source.is_file():
        files = [source]
    elif source.is_dir():
        preferred = source / "results.json"
        files = [preferred] if preferred.exists() else sorted(
            source.glob("*.json")
        )
    else:
        return {}

    results: dict[str, dict[str, object]] = {}

    for filename in files:
        try:
            with filename.open(encoding="utf-8") as file:
                payload = json.load(file)
        except (OSError, json.JSONDecodeError) as error:
            print(f"  Skipping {filename}: {error}")
            continue

        if not isinstance(payload, dict):
            continue

        if is_algorithm_result(payload):
            name = payload.get("rating", {}).get("name")
            if isinstance(name, str):
                if name in results:
                    raise ValueError(
                        f"Duplicate result for algorithm {name!r}."
                    )
                results[name] = payload
            continue

        for name, value in payload.items():
            if isinstance(name, str) and is_algorithm_result(value):
                if name in results:
                    raise ValueError(
                        f"Duplicate result for algorithm {name!r}."
                    )
                results[name] = value

    return results


def algorithm_color(name: str) -> str:
    """Return the configured color for an algorithm."""
    return ALGORITHM_DISPLAY.get(name, (name, "#888888"))[1]


def algorithm_label(name: str) -> str:
    """Return the configured short display name for an algorithm."""
    return ALGORITHM_DISPLAY.get(name, (name, "#888888"))[0]


def nested_metric(
    result: dict[str, object],
    section: str,
    key: str,
) -> float | None:
    """Read a finite numeric value from a nested result section."""
    values = result.get(section)
    if not isinstance(values, dict):
        return None

    value = values.get(key)
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return None

    numeric = float(value)
    return numeric if np.isfinite(numeric) else None


def common_ranking_k(
    results: dict[str, dict[str, object]],
    algorithms: list[str],
) -> int:
    """Return the common ranking cutoff or reject inconsistent results."""
    values: set[int] = set()

    for name in algorithms:
        ranking = results[name].get("ranking")
        if not isinstance(ranking, dict):
            raise ValueError(f"{name} has no ranking result section.")

        raw_k = ranking.get("k")
        if isinstance(raw_k, bool) or not isinstance(raw_k, int):
            raise ValueError(f"{name} has an invalid ranking cutoff.")
        if raw_k <= 0:
            raise ValueError(f"{name} has a nonpositive ranking cutoff.")
        values.add(raw_k)

    if len(values) != 1:
        raise ValueError(
            "Algorithms use inconsistent ranking cutoffs: "
            f"{sorted(values)}."
        )
    return values.pop()


def ordered_algorithms(
    results: dict[str, dict[str, object]],
    required: tuple[str, str] | None = None,
) -> list[str]:
    """Return known algorithms in the canonical display order."""
    names: list[str] = []

    for name in ALGORITHM_ORDER:
        if name not in results:
            continue
        if required is not None:
            section, key = required
            if nested_metric(results[name], section, key) is None:
                continue
        names.append(name)

    # Preserve unexpected future algorithms after the canonical entries.
    for name in results:
        if name in names:
            continue
        if required is not None:
            section, key = required
            if nested_metric(results[name], section, key) is None:
                continue
        names.append(name)

    return names


def save_figure(
    figure: matplotlib.figure.Figure,
    output_path: Path,
    output_format: str,
) -> None:
    """Save and close a figure."""
    options: dict[str, object] = {
        "facecolor": "white",
        "bbox_inches": "tight",
        "pad_inches": 0.15,
    }
    if output_format == "png":
        options["dpi"] = 600

    figure.savefig(output_path, format=output_format, **options)
    plt.close(figure)
    print(f"  Saved: {output_path}")


def _save_figure_to_all(
    figure: matplotlib.figure.Figure,
    output_paths: list[Path],
    output_format: str,
) -> None:
    """Save one figure to several paths, then close it once."""
    options: dict[str, object] = {
        "facecolor": "white",
        "bbox_inches": "tight",
        "pad_inches": 0.15,
    }
    if output_format == "png":
        options["dpi"] = 600

    for output_path in output_paths:
        figure.savefig(output_path, format=output_format, **options)
        print(f"  Saved: {output_path}")
    plt.close(figure)


def add_vertical_value_labels(
    axis: plt.Axes,
    bars: object,
    values: list[float],
    precision: int = 4,
) -> None:
    """Add labels above vertical bars."""
    maximum = max(values, default=0.0)
    offset = maximum * 0.025 if maximum > 0 else 0.01

    for bar, value in zip(bars, values):
        axis.text(
            bar.get_x() + bar.get_width() / 2,
            value + offset,
            f"{value:.{precision}f}",
            ha="center",
            va="bottom",
            fontsize=9,
            fontweight="bold",
        )


def build_rating_errors(
    results: dict[str, dict[str, object]],
) -> matplotlib.figure.Figure | None:
    """Build raw and bounded RMSE/MAE comparisons."""
    algorithms = ordered_algorithms(results, ("rating", "rmse"))
    algorithms = [
        name
        for name in algorithms
        if all(
            nested_metric(results[name], "rating", key) is not None
            for key in ("mae", "bounded_rmse", "bounded_mae")
        )
    ]

    if not algorithms:
        print("  No complete rating-error data to plot.")
        return None

    labels = [algorithm_label(name) for name in algorithms]
    colors = [algorithm_color(name) for name in algorithms]
    x_values = np.arange(len(algorithms))

    chart_specs = [
        ("rmse", "Raw RMSE", "Lower is better"),
        ("mae", "Raw MAE", "Lower is better"),
        (
            "bounded_rmse",
            "Bounded RMSE",
            "Predictions clipped to the valid rating range",
        ),
        (
            "bounded_mae",
            "Bounded MAE",
            "Predictions clipped to the valid rating range",
        ),
    ]

    figure, axes = plt.subplots(2, 2, figsize=(17, 11))
    flat_axes = axes.ravel()

    for axis, (key, title, subtitle) in zip(flat_axes, chart_specs):
        values = [
            float(nested_metric(results[name], "rating", key))
            for name in algorithms
        ]
        bars = axis.bar(
            x_values,
            values,
            width=0.68,
            color=colors,
            edgecolor="white",
            linewidth=0.8,
        )
        axis.set_xticks(x_values)
        axis.set_xticklabels(labels, rotation=30, ha="right")
        axis.set_ylabel(key.replace("_", " ").upper())
        axis.set_title(f"{title}\n{subtitle}")
        maximum = max(values)
        axis.set_ylim(0, maximum * 1.18 if maximum > 0 else 1)
        add_vertical_value_labels(axis, bars, values)

    figure.suptitle(
        "Rating Prediction Error",
        fontsize=17,
        fontweight="bold",
        y=1.01,
    )
    figure.tight_layout()
    return figure


def build_ranking_metrics(
    results: dict[str, dict[str, object]],
) -> matplotlib.figure.Figure | None:
    """Build the nonredundant one-positive ranking metrics."""
    keys = ("hit_rate@k", "ndcg@k", "mrr@k")
    algorithms = ordered_algorithms(results)
    algorithms = [
        name
        for name in algorithms
        if all(
            nested_metric(results[name], "ranking", key) is not None
            for key in keys
        )
    ]

    if not algorithms:
        print("  No complete ranking data to plot.")
        return None

    k = common_ranking_k(results, algorithms)
    labels = [algorithm_label(name) for name in algorithms]
    colors = [algorithm_color(name) for name in algorithms]
    x_values = np.arange(len(algorithms))

    chart_specs = [
        ("hit_rate@k", f"Hit Rate@{k}"),
        ("ndcg@k", f"NDCG@{k}"),
        ("mrr@k", f"Truncated MRR@{k}"),
    ]

    figure, axes = plt.subplots(1, 3, figsize=(19, 6.5))

    for axis, (key, title) in zip(axes, chart_specs):
        values = [
            float(nested_metric(results[name], "ranking", key))
            for name in algorithms
        ]
        bars = axis.bar(
            x_values,
            values,
            width=0.68,
            color=colors,
            edgecolor="white",
            linewidth=0.8,
        )
        axis.set_xticks(x_values)
        axis.set_xticklabels(labels, rotation=30, ha="right")
        axis.set_ylabel(title)
        axis.set_title(f"{title}\nHigher is better")
        maximum = max(values)
        axis.set_ylim(0, maximum * 1.25 if maximum > 0 else 0.1)
        add_vertical_value_labels(axis, bars, values)

    figure.suptitle(
        "Sampled-Candidate Ranking Quality",
        fontsize=17,
        fontweight="bold",
        y=1.02,
    )
    figure.tight_layout()
    return figure


def build_accuracy_vs_ranking(
    results: dict[str, dict[str, object]],
) -> matplotlib.figure.Figure | None:
    """Build a raw RMSE versus NDCG scatter plot."""
    points: list[tuple[str, float, float]] = []
    k = 10

    for name in ordered_algorithms(results):
        rmse = nested_metric(results[name], "rating", "rmse")
        ndcg = nested_metric(results[name], "ranking", "ndcg@k")
        if rmse is None or ndcg is None:
            continue

        points.append((name, rmse, ndcg))

    if len(points) < 2:
        print("  Not enough data for the accuracy-versus-ranking chart.")
        return None

    point_algorithms = [point[0] for point in points]
    k = common_ranking_k(results, point_algorithms)

    figure, axis = plt.subplots(figsize=(12, 8))

    x_values = [point[1] for point in points]
    y_values = [point[2] for point in points]
    x_span = max(x_values) - min(x_values)
    y_span = max(y_values) - min(y_values)

    x_padding = x_span * 0.15 if x_span > 0 else max(x_values[0] * 0.1, 0.1)
    y_padding = y_span * 0.25 if y_span > 0 else 0.05

    axis.set_xlim(min(x_values) - x_padding, max(x_values) + x_padding)
    axis.set_ylim(
        max(0.0, min(y_values) - y_padding),
        max(y_values) + y_padding,
    )

    annotation_offsets = [
        (-36, 18),
        (32, 24),
        (-34, 28),
        (30, -30),
        (-35, -28),
        (34, 20),
        (-32, 20),
        (30, 22),
    ]

    for index, (name, rmse, ndcg) in enumerate(points):
        color = algorithm_color(name)
        axis.scatter(
            rmse,
            ndcg,
            s=350,
            color=color,
            edgecolors="black",
            linewidth=1.2,
            zorder=3,
        )
        axis.annotate(
            algorithm_label(name),
            (rmse, ndcg),
            textcoords="offset points",
            xytext=annotation_offsets[index % len(annotation_offsets)],
            ha="center",
            va="bottom",
            fontsize=11,
            fontweight="bold",
            color=color,
        )

    axis.set_xlabel("Raw RMSE → worse")
    axis.set_ylabel(f"NDCG@{k} ↑ better")
    axis.set_title(
        "Rating Accuracy Versus Ranking Quality\n"
        "Lower RMSE and higher NDCG are preferred"
    )

    axis.text(
        0.98,
        0.96,
        "Pointwise rating accuracy and ranking quality measure "
        "different objectives.",
        transform=axis.transAxes,
        ha="right",
        va="top",
        fontsize=11,
        style="italic",
        bbox={
            "boxstyle": "round,pad=0.5",
            "facecolor": "#FFF9C4",
            "edgecolor": "#F9A825",
            "alpha": 0.9,
        },
    )

    return figure


def build_prediction_times(
    results: dict[str, dict[str, object]],
) -> matplotlib.figure.Figure | None:
    """Build test-set rating prediction-time bars."""
    algorithms = ordered_algorithms(
        results,
        ("timing", "prediction_seconds"),
    )
    if not algorithms:
        print("  No prediction timing data to plot.")
        return None

    algorithms.sort(
        key=lambda name: float(
            nested_metric(results[name], "timing", "prediction_seconds")
        )
    )
    labels = [algorithm_label(name) for name in algorithms]
    values = [
        float(
            nested_metric(results[name], "timing", "prediction_seconds")
        )
        for name in algorithms
    ]
    colors = [algorithm_color(name) for name in algorithms]

    figure, axis = plt.subplots(
        figsize=(11, 0.75 * len(algorithms) + 2)
    )
    bars = axis.barh(
        labels,
        values,
        color=colors,
        edgecolor="white",
        linewidth=0.8,
        height=0.62,
    )
    axis.invert_yaxis()
    axis.set_xlabel("Seconds")
    axis.set_title(
        "Test-Set Rating Prediction Time\n"
        "Includes test-row prediction and ranking-candidate scoring"
    )

    maximum = max(values, default=0.0)
    offset = maximum * 0.02 if maximum > 0 else 0.001
    axis.set_xlim(0, maximum * 1.2 if maximum > 0 else 1)

    for bar, value in zip(bars, values):
        axis.text(
            value + offset,
            bar.get_y() + bar.get_height() / 2,
            f"{value:.3f} s",
            va="center",
            fontsize=10,
            fontweight="bold",
        )

    return figure


def build_out_of_range(
    results: dict[str, dict[str, object]],
) -> matplotlib.figure.Figure | None:
    """Plot the percentage of raw predictions outside 0.5 to 5.0."""
    algorithms = ordered_algorithms(
        results,
        ("rating", "out_of_range_pct"),
    )
    if not algorithms:
        print("  No out-of-range prediction data to plot.")
        return None

    labels = [algorithm_label(name) for name in algorithms]
    values = [
        float(nested_metric(results[name], "rating", "out_of_range_pct"))
        for name in algorithms
    ]
    colors = [algorithm_color(name) for name in algorithms]
    x_values = np.arange(len(algorithms))

    figure, axis = plt.subplots(figsize=(13, 6))
    bars = axis.bar(
        x_values,
        values,
        width=0.68,
        color=colors,
        edgecolor="white",
        linewidth=0.8,
    )
    axis.set_xticks(x_values)
    axis.set_xticklabels(labels, rotation=30, ha="right")
    axis.set_ylabel("Out-of-range predictions (%)")
    axis.set_title(
        "Raw Predictions Outside the Valid Rating Range\n"
        "Bounded metrics clip these predictions to [0.5, 5.0]"
    )

    maximum = max(values, default=0.0)
    axis.set_ylim(0, maximum * 1.2 if maximum > 0 else 1)
    add_vertical_value_labels(axis, bars, values, precision=2)
    return figure


def build_training_times(
    results: dict[str, dict[str, object]],
) -> matplotlib.figure.Figure | None:
    """Build positive training/model-selection time bars."""
    algorithms = ordered_algorithms(
        results,
        ("timing", "training_seconds"),
    )
    trained = [
        name
        for name in algorithms
        if float(
            nested_metric(results[name], "timing", "training_seconds")
        ) > 0
    ]

    if not trained:
        print("  No algorithms report positive training time.")
        return None

    trained.sort(
        key=lambda name: float(
            nested_metric(results[name], "timing", "training_seconds")
        )
    )
    labels = [algorithm_label(name) for name in trained]
    values = [
        float(nested_metric(results[name], "timing", "training_seconds"))
        for name in trained
    ]
    colors = [algorithm_color(name) for name in trained]

    figure, axis = plt.subplots(
        figsize=(11, 0.85 * len(trained) + 2.5)
    )
    bars = axis.barh(
        labels,
        values,
        color=colors,
        edgecolor="white",
        linewidth=0.8,
        height=0.62,
    )
    axis.invert_yaxis()
    axis.set_xlabel("Seconds")
    axis.set_title(
        "Training and Model-Selection Time\n"
        "Reported for algorithms timed by algorithms.py"
    )

    maximum = max(values, default=0.0)
    offset = maximum * 0.02 if maximum > 0 else 0.001
    axis.set_xlim(0, maximum * 1.2 if maximum > 0 else 1)

    for bar, value in zip(bars, values):
        axis.text(
            value + offset,
            bar.get_y() + bar.get_height() / 2,
            f"{value:.2f} s",
            va="center",
            fontsize=10,
            fontweight="bold",
        )

    return figure


# ---------------------------------------------------------------------------
# Figures 07-13 (MF+BPR hybrid diagnostics). These read the saved per-user
# ranking-score matrices and the candidate file directly (in addition to the
# results.json aggregate), because they need per-user / per-candidate detail
# that the aggregate results do not carry.
# ---------------------------------------------------------------------------

PREDICTIONS_DIR = BASE_DIR / "Predictions"
PROCESSED_DIR = BASE_DIR / "ProcessedData"


def _load_ranking_scores(stage: str) -> np.ndarray | None:
    path = PREDICTIONS_DIR / f"{stage}_ranking_scores.npy"
    if not path.exists():
        return None
    return np.load(path)


def _load_test_ranking() -> dict[str, np.ndarray] | None:
    path = PROCESSED_DIR / "ranking_test_1000.npz"
    if not path.exists():
        return None
    with np.load(path) as z:
        return {
            "users": z["users"],
            "candidates": z["candidates"],
            "positive_indices": z["positive_indices"],
        }


def _load_validation_ranking() -> dict[str, np.ndarray] | None:
    path = PROCESSED_DIR / "ranking_validation_1000.npz"
    if not path.exists():
        return None
    with np.load(path) as z:
        return {
            "users": z["users"],
            "candidates": z["candidates"],
            "positive_indices": z["positive_indices"],
        }


def _positive_rank(scores: np.ndarray, pos: np.ndarray, k: int = 10):
    """Return the 1-based rank of the relevant movie for each candidate row.

    A row with rank > k is reported as k + 1 (a miss beyond the cutoff).
    """
    n = len(pos)
    ranks = np.empty(n, dtype=np.int64)
    for i in range(n):
        order = np.argsort(-scores[i], kind="stable")
        ranks[i] = int(np.where(order == pos[i])[0][0]) + 1
    return ranks


def _zscore_rows(rows: np.ndarray, eps: float = 1e-12) -> np.ndarray:
    rows = np.asarray(rows, dtype=np.float64)
    mean = rows.mean(axis=1, keepdims=True)
    std = rows.std(axis=1, keepdims=True)
    std = np.maximum(std, eps)
    return (rows - mean) / std


def build_hybrid_rank_distribution(
    results: dict[str, dict[str, object]],
) -> matplotlib.figure.Figure | None:
    """Fig 07: distribution of the relevant movie's rank across 500 users.

    A log-scale histogram for MF, BPR-MF, and MF+BPR. Shows that BPR-based
    methods push the relevant movie into far lower ranks (closer to the top)
    than rating-trained MF.
    """
    mf = _load_ranking_scores("mf")
    bpr = _load_ranking_scores("bpr")
    hybrid = _load_ranking_scores("mf_bpr")
    rk = _load_test_ranking()
    if not (mf is not None and bpr is not None and hybrid is not None and rk is not None):
        print("  Fig 07 skipped: missing ranking scores or candidate file.")
        return None
    pos = rk["positive_indices"]
    figure, axes = plt.subplots(1, 3, figsize=(17, 5))
    for axis, scores, label, color in [
        (axes[0], mf, "Biased MF", "#0072B2"),
        (axes[1], bpr, "BPR-MF", "#984EA3"),
        (axes[2], hybrid, "MF+BPR", "#E41A1C"),
    ]:
        ranks = _positive_rank(scores, pos)
        # Cap display at rank 1000 (the full candidate width); log scale.
        capped = np.clip(ranks, 1, 1000)
        axis.hist(capped, bins=20, range=(1, 1000), color=color, alpha=0.75,
                  edgecolor="white")
        axis.set_xscale("log")
        axis.set_xlabel("Rank of relevant movie (log scale)")
        axis.set_ylabel("Number of users")
        med = int(np.median(capped))
        axis.set_title(f"{label}\nmedian rank {med}")
        axis.axvline(10, color="k", ls="--", lw=1, alpha=0.6)
        axis.text(10.2, axis.get_ylim()[1] * 0.9, "top-10", fontsize=9,
                  rotation=90, va="top")
    figure.suptitle(
        "Distribution of the Relevant Movie's Rank (500 test users)",
        fontsize=16, fontweight="bold", y=1.02,
    )
    figure.tight_layout()
    return figure


def build_hybrid_lambda_sweep(
    results: dict[str, dict[str, object]],
) -> matplotlib.figure.Figure | None:
    """Fig 08: dual-headed lambda sweep.

    Left: rating-head validation RMSE vs lambda (lower better).
    Right: ranking-head validation NDCG@10 vs lambda (higher better).
    Markers show the selected lambda for each head.
    """
    val = _load_validation_ranking()
    mf_scores_val = _load_ranking_scores("mf")  # test scores; for the sweep
    # We need validation scores for both heads. Re-derive the rating-head
    # sweep from the validation predictions if available; otherwise use the
    # test-row components (still informative for the shape of the curve).
    # For fidelity, load the validation components computed by the stage.
    mf_val_pred_path = PREDICTIONS_DIR / "mf_bpr_val_mf_rating.npy"
    bpr_val_pred_path = PREDICTIONS_DIR / "mf_bpr_val_bpr_rating.npy"
    val_actual_path = PREDICTIONS_DIR / "mf_bpr_val_actual.npy"
    if not (mf_val_pred_path.exists() and bpr_val_pred_path.exists()
            and val_actual_path.exists() and val is not None
            and mf_scores_val is not None):
        # Fall back: build the sweep from the test-row components + test
        # candidates. This reproduces the shape, and the selected lambdas are
        # read from the stage meta (ground truth).
        print("  Fig 08: using test-row components for the sweep.")
        mf_pred = np.load(PREDICTIONS_DIR / "mf_predictions.npy")
        bpr_pred = np.load(PREDICTIONS_DIR / "bpr_predictions.npy")
        test = np.load(PROCESSED_DIR / "interactions_test.npy")
        actual = test[:, 2]
        mf_scores = mf_scores_val
        bpr_scores = _load_ranking_scores("bpr")
        rk = _load_test_ranking()
        users, cands, pos = rk["users"], rk["candidates"], rk["positive_indices"]
    else:
        mf_pred = np.load(mf_val_pred_path)
        bpr_pred = np.load(bpr_val_pred_path)
        actual = np.load(val_actual_path)
        mf_scores = mf_scores_val
        bpr_scores = _load_ranking_scores("bpr")
        users, cands, pos = val["users"], val["candidates"], val["positive_indices"]

    if mf_scores is None or bpr_scores is None:
        print("  Fig 08 skipped: missing ranking scores.")
        return None

    # Read the selected lambdas from the stage meta (authoritative).
    meta = json.loads((PREDICTIONS_DIR / "mf_bpr_meta.json").read_text())
    lambda_r = float(meta.get("lambda_rating", 1.0))
    lambda_k = float(meta.get("lambda_ranking", 0.3))

    grid = np.linspace(0.0, 1.0, 11)
    rmse_curve = []
    for lam in grid:
        pred = lam * mf_pred + (1.0 - lam) * bpr_pred
        rmse_curve.append(float(np.sqrt(np.mean((pred - actual) ** 2))))
    ndcg_curve = []
    z_mf = _zscore_rows(mf_scores)
    z_bpr = _zscore_rows(bpr_scores)
    for lam in grid:
        blend = lam * z_mf + (1.0 - lam) * z_bpr
        ranks = _positive_rank(blend, pos)
        hit = (ranks <= 10).astype(float)
        ndcg = np.where(ranks <= 10, 1.0 / np.log2(ranks + 1), 0.0)
        ndcg_curve.append(float(ndcg.mean()))

    figure, axes = plt.subplots(1, 2, figsize=(14, 5.5))
    axes[0].plot(grid, rmse_curve, "-o", color="#0072B2", lw=2)
    axes[0].axvline(lambda_r, color="k", ls="--", lw=1.5, label=f"selected λ={lambda_r:.1f}")
    axes[0].set_xlabel("λ (fraction of Biased MF)")
    axes[0].set_ylabel("Validation RMSE (↓)")
    axes[0].set_title("Rating Head: RMSE vs λ")
    axes[0].legend()
    axes[0].set_xticks(grid)
    axes[1].plot(grid, ndcg_curve, "-o", color="#E41A1C", lw=2)
    axes[1].axvline(lambda_k, color="k", ls="--", lw=1.5, label=f"selected λ={lambda_k:.1f}")
    axes[1].set_xlabel("λ (fraction of Biased MF)")
    axes[1].set_ylabel("Validation NDCG@10 (↑)")
    axes[1].set_title("Ranking Head: NDCG@10 vs λ")
    axes[1].legend()
    axes[1].set_xticks(grid)
    figure.suptitle(
        "MF+BPR Dual-Headed λ Selection (validation)",
        fontsize=16, fontweight="bold", y=1.02,
    )
    figure.tight_layout()
    return figure


def build_raw_score_scales(
    results: dict[str, dict[str, object]],
) -> matplotlib.figure.Figure | None:
    """Fig 09: raw score distributions of MF vs BPR (justifies z-scoring).

    Two overlaid histograms (one per user's candidate row, aggregated) show
    the two algorithms' raw score scales are incompatible in magnitude,
    motivating per-row z-score standardisation before blending.
    """
    mf = _load_ranking_scores("mf")
    bpr = _load_ranking_scores("bpr")
    if mf is None or bpr is None:
        print("  Fig 09 skipped: missing ranking scores.")
        return None
    figure, axes = plt.subplots(1, 2, figsize=(14, 5))
    axes[0].hist(mf.flatten(), bins=60, color="#0072B2", alpha=0.7,
                 edgecolor="white", label=f"MF (mean {mf.mean():.2f})")
    axes[0].hist(bpr.flatten(), bins=60, color="#984EA3", alpha=0.7,
                 edgecolor="white", label=f"BPR (mean {bpr.mean():.2f})")
    axes[0].set_xlabel("Raw score")
    axes[0].set_ylabel("Density (count)")
    axes[0].set_title("Raw candidate-score scales (all users pooled)")
    axes[0].legend()
    # Per-user row means to show row-to-row variation (why per-row, not
    # global, standardisation).
    mf_row_mean = mf.mean(axis=1)
    bpr_row_mean = bpr.mean(axis=1)
    axes[1].plot(mf_row_mean, color="#0072B2", alpha=0.6, label="MF row mean")
    axes[1].plot(bpr_row_mean, color="#984EA3", alpha=0.6, label="BPR row mean")
    axes[1].set_xlabel("User (candidate row)")
    axes[1].set_ylabel("Row mean score")
    axes[1].set_title("Row-to-row scale variation")
    axes[1].legend()
    figure.suptitle(
        "Incompatible Raw Score Scales: MF vs BPR-MF",
        fontsize=16, fontweight="bold", y=1.02,
    )
    figure.tight_layout()
    return figure


def build_latent_factor_geometry(
    results: dict[str, dict[str, object]],
) -> matplotlib.figure.Figure | None:
    """Fig 10: 2-D projection of MF and BPR latent factors (t-SNE-like PCA).

    Projects the 50-dim user factors of each model onto the first two
    principal components, showing the two models learn different geometry
    from the same architecture.
    """
    import os
    mf_model_path = PREDICTIONS_DIR / "mf_model.npz"
    bpr_model_path = PREDICTIONS_DIR / "bpr_model.npz"
    if not (mf_model_path.exists() and bpr_model_path.exists()):
        print("  Fig 10 skipped: missing model files.")
        return None
    with np.load(mf_model_path) as z:
        mf_users = z["user_factors"].copy()
    with np.load(bpr_model_path) as z:
        bpr_users = z["user_factors"].copy()
    # Subsample to keep PCA fast (e.g. first 5000 users).
    n = min(5000, mf_users.shape[0])
    figure, axes = plt.subplots(1, 2, figsize=(14, 6))
    for axis, users, label, color in [
        (axes[0], mf_users[:n], "Biased MF", "#0072B2"),
        (axes[1], bpr_users[:n], "BPR-MF", "#984EA3"),
    ]:
        mean = users.mean(axis=0)
        centered = users - mean
        # PCA via SVD (deterministic, no randomness).
        U, S, Vt = np.linalg.svd(centered, full_matrices=False)
        pc1 = centered @ Vt[0]
        pc2 = centered @ Vt[1]
        axis.scatter(pc1, pc2, s=2, color=color, alpha=0.35, marker=".",
                     linewidths=0)
        var_explained = (S ** 2).sum()
        axis.set_xlabel(f"PC1 ({100 * S[0] ** 2 / var_explained:.1f}% var)")
        axis.set_ylabel(f"PC2 ({100 * S[1] ** 2 / var_explained:.1f}% var)")
        axis.set_title(f"{label}: user latent factors (PCA)")
    figure.suptitle(
        "Latent-Factor Geometry: Same Architecture, Different Objectives",
        fontsize=15, fontweight="bold", y=1.02,
    )
    figure.tight_layout()
    return figure


def build_hybrid_score_decomposition(
    results: dict[str, dict[str, object]],
) -> matplotlib.figure.Figure | None:
    """Fig 11: per-row decomposition of the MF+BPR blended z-score.

    For a sample of users, show the blended z-score row as a stacked
    contribution from the MF component (λ·z_MF) and the BPR component
    ((1−λ)·z_BPR). Illustrates that the blend is a convex combination in
    rank space.
    """
    mf = _load_ranking_scores("mf")
    bpr = _load_ranking_scores("bpr")
    if mf is None or bpr is None:
        print("  Fig 11 skipped: missing ranking scores.")
        return None
    meta = json.loads((PREDICTIONS_DIR / "mf_bpr_meta.json").read_text())
    lambda_k = float(meta.get("lambda_ranking", 0.3))
    z_mf = _zscore_rows(mf)
    z_bpr = _zscore_rows(bpr)
    # Show the first 5 users, each as a small panel; 1000 candidates each.
    figure, axes = plt.subplots(5, 1, figsize=(14, 12))
    x = np.arange(mf.shape[1])
    for i, axis in enumerate(axes):
        contrib_mf = lambda_k * z_mf[i]
        contrib_bpr = (1.0 - lambda_k) * z_bpr[i]
        axis.plot(x, contrib_mf, lw=0.8, color="#0072B2",
                  label=f"MF (λ={lambda_k:.1f})")
        axis.plot(x, contrib_bpr, lw=0.8, color="#984EA3",
                  label=f"BPR (1−λ={1 - lambda_k:.1f})")
        axis.plot(x, contrib_mf + contrib_bpr, lw=1.5, color="#E41A1C",
                  label="Blend")
        if i == 0:
            axis.legend(loc="upper right", fontsize=8)
        axis.set_title(f"User {i} (of 5 shown), 1000 candidates", fontsize=10)
        axis.set_xlabel("Candidate position (unsorted)")
        axis.set_ylabel("z-score contribution")
    figure.suptitle(
        "MF+BPR Ranking-Head Score Decomposition (per-row z-blend)",
        fontsize=15, fontweight="bold", y=1.005,
    )
    figure.tight_layout()
    return figure


def build_rank_gap_from_models(
    results: dict[str, dict[str, object]],
) -> matplotlib.figure.Figure | None:
    """Fig 12: scatter of the relevant movie's rank under MF, BPR, MF+BPR.

    Left: rank under MF (x) vs rank under BPR (y), each user a point.
    Right: rank under BPR (x) vs rank under MF+BPR (y) — the hybrid's
    improvement over its ranking constituent.
    """
    mf = _load_ranking_scores("mf")
    bpr = _load_ranking_scores("bpr")
    hybrid = _load_ranking_scores("mf_bpr")
    rk = _load_test_ranking()
    if not (mf is not None and bpr is not None and hybrid is not None
            and rk is not None):
        print("  Fig 12 skipped: missing ranking scores or candidate file.")
        return None
    pos = rk["positive_indices"]
    r_mf = _positive_rank(mf, pos)
    r_bpr = _positive_rank(bpr, pos)
    r_hyb = _positive_rank(hybrid, pos)
    figure, axes = plt.subplots(1, 2, figsize=(14, 6))
    axes[0].scatter(r_mf, r_bpr, s=8, alpha=0.4, color="#444")
    lim0 = min(1000, max(r_mf.max(), r_bpr.max()))
    axes[0].plot([0, lim0], [0, lim0], "k--", lw=1, alpha=0.5,
                 label="rank MF = rank BPR")
    axes[0].set_xlabel("Rank under Biased MF")
    axes[0].set_ylabel("Rank under BPR-MF")
    axes[0].set_xscale("log"); axes[0].set_yscale("log")
    axes[0].set_title("MF vs BPR-MF (per user)")
    axes[0].legend(fontsize=9)
    axes[1].scatter(r_bpr, r_hyb, s=8, alpha=0.4, color="#E41A1C")
    lim1 = min(1000, max(r_bpr.max(), r_hyb.max()))
    axes[1].plot([0, lim1], [0, lim1], "k--", lw=1, alpha=0.5,
                 label="rank BPR = rank hybrid")
    axes[1].set_xlabel("Rank under BPR-MF")
    axes[1].set_ylabel("Rank under MF+BPR")
    axes[1].set_xscale("log"); axes[1].set_yscale("log")
    axes[1].set_title("BPR-MF vs MF+BPR (per user)")
    axes[1].legend(fontsize=9)
    figure.suptitle(
        "Rank of the Relevant Movie Across Models (log-log)",
        fontsize=16, fontweight="bold", y=1.02,
    )
    figure.tight_layout()
    return figure


def build_bpr_calibration(
    results: dict[str, dict[str, object]],
) -> matplotlib.figure.Figure | None:
    """Fig 13: BPR raw score vs its post-hoc affine-mapped rating.

    Shows the fitted affine mapping and how much of the [0.5, 5.0] rating
    space is actually reachable. The mapping is degenerate (slope ≈ 0)
    because BPR's validation scores carry no linear rating signal.
    """
    meta = json.loads((PREDICTIONS_DIR / "bpr_meta.json").read_text())
    affine = meta.get("affine_mapping", {})
    slope = float(affine.get("slope", 0.0))
    intercept = float(affine.get("intercept", 0.0))
    bpr = _load_ranking_scores("bpr")
    if bpr is None:
        print("  Fig 13 skipped: missing BPR ranking scores.")
        return None
    # Use the BPR raw scores on the validation rows to show the mapping.
    val = _load_validation_ranking()
    bpr_model_path = PREDICTIONS_DIR / "bpr_model.npz"
    figure, axes = plt.subplots(1, 2, figsize=(14, 5.5))
    # Left: histogram of BPR raw scores + the mapped range.
    scores = bpr.flatten()
    axes[0].hist(scores, bins=60, color="#984EA3", alpha=0.75,
                 edgecolor="white")
    axes[0].set_xlabel("BPR raw score")
    axes[0].set_ylabel("Density")
    mapped_range = [slope * scores.min() + intercept, slope * scores.max() + intercept]
    axes[0].axhline(0, color="k", lw=0.5)
    axes[0].set_title(
        f"BPR raw score distribution\n"
        f"affine map: slope={slope:.3f}, intercept={intercept:.3f}\n"
        f"mapped range ≈ [{min(mapped_range):.2f}, {max(mapped_range):.2f}]"
    )
    # Right: the affine mapping curve over the observed score range, with the
    # valid rating band [0.5, 5.0] shaded.
    s = np.linspace(scores.min(), scores.max(), 200)
    axes[1].plot(s, slope * s + intercept, "-", color="#984EA3", lw=2,
                 label="fitted affine map")
    axes[1].fill_between(s, 0.5, 5.0, color="0.9", alpha=0.5,
                         label="valid rating band [0.5, 5.0]")
    axes[1].set_xlabel("BPR raw score")
    axes[1].set_ylabel("Mapped rating")
    axes[1].set_title("Post-hoc BPR → rating mapping")
    axes[1].legend(fontsize=9)
    figure.suptitle(
        "BPR-MF Rating Calibration (post-hoc affine mapping)",
        fontsize=16, fontweight="bold", y=1.02,
    )
    figure.tight_layout()
    return figure


def generate_all(
    results: dict[str, dict[str, object]],
    output_dir: str | Path,
    output_format: str = "svg",
) -> None:
    """Generate all charts from current-format results."""
    if output_format not in SUPPORTED_FORMATS:
        supported = ", ".join(sorted(SUPPORTED_FORMATS))
        raise ValueError(
            f"Unsupported output format {output_format!r}. "
            f"Choose one of: {supported}."
        )

    destination = Path(output_dir)
    destination.mkdir(parents=True, exist_ok=True)

    print(
        f"\nGenerating {output_format.upper()} charts in "
        f"{destination}\n"
    )

    chart_specs: list[
        tuple[
            str,
            Callable[
                [dict[str, dict[str, object]]],
                matplotlib.figure.Figure | None,
            ],
        ]
    ] = [
        ("01_rating_errors", build_rating_errors),
        ("02_ranking_metrics", build_ranking_metrics),
        ("03_accuracy_vs_ranking", build_accuracy_vs_ranking),
        ("04_prediction_time", build_prediction_times),
        ("05_out_of_range_predictions", build_out_of_range),
        ("06_training_time", build_training_times),
        ("07_hybrid_rank_distribution", build_hybrid_rank_distribution),
        ("08_hybrid_lambda_sweep", build_hybrid_lambda_sweep),
        ("09_raw_score_scales", build_raw_score_scales),
        ("10_latent_factor_geometry", build_latent_factor_geometry),
        ("11_hybrid_score_decomposition", build_hybrid_score_decomposition),
        ("12_rank_gap_from_models", build_rank_gap_from_models),
        ("13_bpr_calibration", build_bpr_calibration),
    ]

    # Mirror PDFs into the essay's figures directory so ib_cs_ee/figures/*.pdf
    # (referenced by essay.qmd) is regenerated alongside charts/.
    essay_destination = None
    if output_format == "pdf" and ESSAY_FIGURES_DIR.exists():
        essay_destination = ESSAY_FIGURES_DIR

    for filename, builder in chart_specs:
        figure = builder(results)
        if figure is None:
            continue
        # save_figure closes the figure, so save to every destination before
        # closing: always charts/, plus the essay figures dir for PDFs.
        figure_paths = [destination / f"{filename}.{output_format}"]
        if essay_destination is not None:
            figure_paths.append(
                essay_destination / f"{filename}.{output_format}"
            )
        _save_figure_to_all(figure, figure_paths, output_format)

    print(f"\nDone. Charts are in {destination}.")
    if essay_destination is not None:
        print(f"Essay figures updated in {essay_destination}.")


def main() -> None:
    """Load or generate results and create all charts."""
    results_path = (
        Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_RESULTS_DIR
    )
    output_format = sys.argv[2].lower() if len(sys.argv) > 2 else "svg"

    if output_format not in SUPPORTED_FORMATS:
        supported = ", ".join(sorted(SUPPORTED_FORMATS))
        raise SystemExit(
            f"Unsupported format {output_format!r}; use {supported}."
        )

    results = load_results(results_path)

    if not results:
        # The visualizer never generates results itself. If it cannot find
        # current-format algorithm results, it terminates and names the file
        # that is required. Run algorithms.py first to produce it.
        if results_path.is_file():
            raise SystemExit(
                f"No current-format algorithm results found in "
                f"{results_path.name}. Run 'python algorithms.py' to "
                f"generate them, then re-run the visualizer."
            )
        required = (
            results_path / "results.json"
            if results_path.is_dir()
            else results_path
        )
        raise SystemExit(
            f"No algorithm results found. Required file: {required}. "
            f"Run 'python algorithms.py' (then 'python algorithms.py "
            f"--merge') to generate it, then re-run the visualizer."
        )

    generate_all(results, OUTPUT_DIR, output_format)


if __name__ == "__main__":
    main()
